# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable

  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer

  # property :title_sort, predicate: ::RDF::URI.new('http://www.teeal.org/ns#collectionTitleSortField'), multiple: true do |index|
  #   index.as :stored_searchable, :stored_sortable
  # end

  # include this at the end to prevent ActiveTriples::UndefinedPropertyError
  include Hyrax::BasicMetadata
end
